// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8RXm2xTGEjcLN-CJGsuHAYsBMOts0hJ0',
    appId: '1:655963122485:web:261af9e3f1d5cc643dba7c',
    messagingSenderId: '655963122485',
    projectId: 'anymex-ryan7',
    authDomain: 'anymex-ryan7.firebaseapp.com',
    storageBucket: 'anymex-ryan7.firebasestorage.app',
    measurementId: 'G-48E9LEBS4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5sGDX3VFXZn8Co4FaeODwQzqT3H1ifK0',
    appId: '1:655963122485:android:928a151d682058a33dba7c',
    messagingSenderId: '655963122485',
    projectId: 'anymex-ryan7',
    storageBucket: 'anymex-ryan7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU3YlOxo4l0KhgW2Mm1MjPG3T2e-4GY4E',
    appId: '1:655963122485:ios:072917f2c716788e3dba7c',
    messagingSenderId: '655963122485',
    projectId: 'anymex-ryan7',
    storageBucket: 'anymex-ryan7.firebasestorage.app',
    iosBundleId: 'com.ryan.anymex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU3YlOxo4l0KhgW2Mm1MjPG3T2e-4GY4E',
    appId: '1:655963122485:ios:072917f2c716788e3dba7c',
    messagingSenderId: '655963122485',
    projectId: 'anymex-ryan7',
    storageBucket: 'anymex-ryan7.firebasestorage.app',
    iosBundleId: 'com.ryan.anymex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8RXm2xTGEjcLN-CJGsuHAYsBMOts0hJ0',
    appId: '1:655963122485:web:b6088f5e63b0d4773dba7c',
    messagingSenderId: '655963122485',
    projectId: 'anymex-ryan7',
    authDomain: 'anymex-ryan7.firebaseapp.com',
    storageBucket: 'anymex-ryan7.firebasestorage.app',
    measurementId: 'G-64XCNKN5CG',
  );
}
