String completeLanguageName(String lang) {
  lang = lang.toLowerCase();
  for (var element in sortedLanguagesMap.entries) {
    if (element.value.toLowerCase() == lang) {
      return element.key;
    }
  }
  return lang.toUpperCase();
}

String completeLanguageCode(String lang) {
  lang = lang.toLowerCase();
  for (var element in sortedLanguagesMap.entries) {
    if (element.key.toLowerCase() == lang) {
      return element.value;
    }
  }
  return lang.toUpperCase();
}

const Map<String, String> extensionLanguageNameByCode = {
  "all": "All Languages",
  "af": "Afrikaans",
  "am": "Amharic",
  "ar": "Arabic",
  "as": "Assamese",
  "az": "Azerbaijani",
  "be": "Belarusian",
  "bg": "Bulgarian",
  "bn": "Bengali",
  "bs": "Bosnian",
  "ca": "Catalan",
  "ceb": "Cebuano",
  "cs": "Czech",
  "da": "Danish",
  "de": "German",
  "el": "Greek",
  "en": "English",
  "en-us": "English (United States)",
  "eo": "Esperanto",
  "es": "Spanish",
  "es-419": "Spanish (Latin America)",
  "et": "Estonian",
  "eu": "Basque",
  "fa": "Persian",
  "fi": "Finnish",
  "fil": "Filipino",
  "fo": "Faroese",
  "fr": "French",
  "ga": "Irish",
  "gn": "Guarani",
  "gu": "Gujarati",
  "ha": "Hausa",
  "he": "Hebrew",
  "hi": "Hindi",
  "hr": "Croatian",
  "ht": "Haitian Creole",
  "hu": "Hungarian",
  "hy": "Armenian",
  "id": "Indonesian",
  "ig": "Igbo",
  "is": "Icelandic",
  "it": "Italian",
  "ja": "Japanese",
  "jv": "Javanese",
  "ka": "Georgian",
  "kk": "Kazakh",
  "km": "Khmer",
  "kn": "Kannada",
  "ko": "Korean",
  "ku": "Kurdish",
  "ky": "Kyrgyz",
  "la": "Latin",
  "lb": "Luxembourgish",
  "lo": "Lao",
  "lt": "Lithuanian",
  "lv": "Latvian",
  "mg": "Malagasy",
  "mi": "Maori",
  "mk": "Macedonian",
  "ml": "Malayalam",
  "mn": "Mongolian",
  "mr": "Marathi",
  "ms": "Malay",
  "mt": "Maltese",
  "my": "Burmese",
  "nb-no": "Norwegian Bokmal",
  "ne": "Nepali",
  "nl": "Dutch",
  "no": "Norwegian",
  "ny": "Nyanja",
  "pl": "Polish",
  "ps": "Pashto",
  "pt": "Portuguese",
  "pt-br": "Portuguese (Brazil)",
  "pt-pt": "Portuguese (Portugal)",
  "rm": "Romansh",
  "ro": "Romanian",
  "ru": "Russian",
  "sd": "Sindhi",
  "sh": "Serbo-Croatian",
  "si": "Sinhalese",
  "sk": "Slovak",
  "sl": "Slovenian",
  "sm": "Samoan",
  "sn": "Shona",
  "so": "Somali",
  "sq": "Albanian",
  "sr": "Serbian",
  "st": "Sesotho",
  "sv": "Swedish",
  "sw": "Swahili",
  "ta": "Tamil",
  "te": "Telugu",
  "tg": "Tajik",
  "th": "Thai",
  "ti": "Tigrinya",
  "tl": "Tagalog",
  "tk": "Turkmen",
  "to": "Tongan",
  "tr": "Turkish",
  "tt": "Tatar",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "uz": "Uzbek",
  "vi": "Vietnamese",
  "xh": "Xhosa",
  "yo": "Yoruba",
  "zh": "Chinese",
  "zh-hk": "Chinese (Hong Kong)",
  "zh-tw": "Chinese (Traditional)",
  "zu": "Zulu",
};

const Map<String, String> extensionLanguageFlagUrlByCode = {
  "all": "https://flagcdn.com/w80/un.png",
  "en": "https://flagcdn.com/w80/gb.png",
  "en-us": "https://flagcdn.com/w80/us.png",
  "es": "https://flagcdn.com/w80/es.png",
  "es-419": "https://flagcdn.com/w80/mx.png",
  "pt": "https://flagcdn.com/w80/pt.png",
  "pt-br": "https://flagcdn.com/w80/br.png",
  "pt-pt": "https://flagcdn.com/w80/pt.png",
  "zh": "https://flagcdn.com/w80/cn.png",
  "zh-hk": "https://flagcdn.com/w80/hk.png",
  "zh-tw": "https://flagcdn.com/w80/tw.png",
  "ja": "https://flagcdn.com/w80/jp.png",
  "ko": "https://flagcdn.com/w80/kr.png",
};

const String _unknownLanguageFlagUrl = "https://flagcdn.com/w80/un.png";

const Map<String, String> _defaultFlagCountryByLanguageCode = {
  "af": "za",
  "am": "et",
  "ar": "sa",
  "as": "in",
  "az": "az",
  "be": "by",
  "bg": "bg",
  "bn": "bd",
  "bs": "ba",
  "ca": "es",
  "ceb": "ph",
  "cs": "cz",
  "da": "dk",
  "de": "de",
  "el": "gr",
  "eo": "eu",
  "et": "ee",
  "eu": "es",
  "fa": "ir",
  "fi": "fi",
  "fil": "ph",
  "fo": "fo",
  "fr": "fr",
  "ga": "ie",
  "gn": "py",
  "gu": "in",
  "ha": "ng",
  "he": "il",
  "hi": "in",
  "hr": "hr",
  "ht": "ht",
  "hu": "hu",
  "hy": "am",
  "id": "id",
  "ig": "ng",
  "is": "is",
  "it": "it",
  "jv": "id",
  "ka": "ge",
  "kk": "kz",
  "km": "kh",
  "kn": "in",
  "ku": "iq",
  "ky": "kg",
  "la": "va",
  "lb": "lu",
  "lo": "la",
  "lt": "lt",
  "lv": "lv",
  "mg": "mg",
  "mi": "nz",
  "mk": "mk",
  "ml": "in",
  "mn": "mn",
  "mr": "in",
  "ms": "my",
  "mt": "mt",
  "my": "mm",
  "nb": "no",
  "ne": "np",
  "nl": "nl",
  "no": "no",
  "ny": "mw",
  "pl": "pl",
  "ps": "af",
  "rm": "ch",
  "ro": "ro",
  "ru": "ru",
  "sd": "pk",
  "sh": "rs",
  "si": "lk",
  "sk": "sk",
  "sl": "si",
  "sm": "ws",
  "sn": "zw",
  "so": "so",
  "sq": "al",
  "sr": "rs",
  "st": "ls",
  "sv": "se",
  "sw": "tz",
  "ta": "in",
  "te": "in",
  "tg": "tj",
  "th": "th",
  "ti": "er",
  "tl": "ph",
  "tk": "tm",
  "to": "to",
  "tr": "tr",
  "tt": "ru",
  "uk": "ua",
  "ur": "pk",
  "uz": "uz",
  "vi": "vn",
  "xh": "za",
  "yo": "ng",
  "zu": "za",
};

String extensionLanguageName(String? code) {
  final normalizedCode = code?.trim().toLowerCase();
  if (normalizedCode == null || normalizedCode.isEmpty) return "Unknown";

  return extensionLanguageNameByCode[normalizedCode] ??
      completeLanguageName(normalizedCode);
}

String extensionLanguageFlagUrl(String? code) {
  final normalizedCode = code?.trim().toLowerCase();
  if (normalizedCode == null || normalizedCode.isEmpty) {
    return _unknownLanguageFlagUrl;
  }

  final directUrl = extensionLanguageFlagUrlByCode[normalizedCode];
  if (directUrl != null) return directUrl;

  final directCountry = _defaultFlagCountryByLanguageCode[normalizedCode];
  if (directCountry != null) {
    return "https://flagcdn.com/w80/$directCountry.png";
  }

  final baseCode = normalizedCode.split('-').first;
  final baseCountry = _defaultFlagCountryByLanguageCode[baseCode];
  if (baseCountry != null) {
    return "https://flagcdn.com/w80/$baseCountry.png";
  }

  return _unknownLanguageFlagUrl;
}

final sortedLanguagesMap = {
  "all": "All",
  "Afrikaans": "af",
  "አማርኛ": "am",
  "العربية": "ar",
  "অসমীয়া": "as",
  "Azərbaycan": "az",
  "беларуская": "be",
  "български": "bg",
  "বাংলা": "bn",
  "bosanski": "bs",
  "Català": "ca",
  "Cebuano": "ceb",
  "čeština": "cs",
  "dansk": "da",
  "Deutsch": "de",
  "Ελληνικά": "el",
  "English": "en",
  "English (United States)": "en-us",
  "Esperanto": "eo",
  "Español": "es",
  "Español (Latinoamérica)": "es-419",
  "Estonian": "et",
  "euskara": "eu",
  "فارسی": "fa",
  "Filipino": "fil",
  "suomi": "fi",
  "Faroese": "fo",
  "Français": "fr",
  "Irish": "ga",
  "Guarani": "gn",
  "Gujarati": "gu",
  "Hausa": "ha",
  "עברית": "he",
  "हिन्दी, हिंदी": "hi",
  "Hrvatski": "hr",
  "Haitian Creole": "ht",
  "Magyar": "hu",
  "Armenian": "hy",
  "Indonesia": "id",
  "Igbo": "ig",
  "Icelandic": "is",
  "Italiano": "it",
  "日本語": "ja",
  "Javanese": "jv",
  "Georgian": "ka",
  "Kazakh": "kk",
  "Cambodian": "km",
  "Kannada": "kn",
  "한국어": "ko",
  "Kurdî": "ku",
  "Kyrgyz": "ky",
  "Latin": "la",
  "Luxembourgish": "lb",
  "Laothian": "lo",
  "lietuvių kalba": "lt",
  "Latvian": "lv",
  "Malagasy": "mg",
  "Maori": "mi",
  "Macedonian": "mk",
  "മലയാളം": "ml",
  "Монгол": "mn",
  "Marathi": "mr",
  "Malaysia": "ms",
  "Maltese": "mt",
  "ဗမာစာ": "my",
  "Norwegian Bokmål (Norway)": "nb-no",
  "Nepali": "ne",
  "Nederlands": "nl",
  "Norsk": "no",
  "Nyanja": "ny",
  "Polski": "pl",
  "Pashto": "ps",
  "Português": "pt",
  "Português (Brasil)": "pt-br",
  "Portuguese (Portugal)": "pt-pt",
  "Romansh": "rm",
  "Română": "ro",
  "Pусский язык": "ru",
  "Sindhi": "sd",
  "srpskohrvatski": "sh",
  "Sinhalese": "si",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Samoan": "sm",
  "Shona": "sn",
  "Somali": "so",
  "Albanian": "sq",
  "Serbian": "sr",
  "Sesotho": "st",
  "svenska": "sv",
  "Swahili": "sw",
  "Tamil": "ta",
  "Telugu": "te",
  "Tajik": "tg",
  "ไทย": "th",
  "Tigrinya": "ti",
  "Tagalog": "tl",
  "Turkmen": "tk",
  "Tonga": "to",
  "Türkçe": "tr",
  "Tatar": "tt",
  "Українська": "uk",
  "Urdu": "ur",
  "Uzbek": "uz",
  "Tiếng Việt": "vi",
  "isiXhosa": "xh",
  "Yoruba": "yo",
  "中文(Zhōngwén)": "zh",
  "繁體中文(Hong Kong)": "zh-hk",
  "Chinese (Traditional)": "zh-tw",
  "isiZulu": "zu",
};

final subtitleLangMap = {
  "English": "eng",
  "German": "ger",
  "French": "fre",
  "Spanish": "spa",
  "Italian": "ita",
  "Japanese": "jpn",
  "Chinese": "chi",
  "Korean": "kor",
  "Portuguese": "por",
  "Russian": "rus",
  "Arabic": "ara",
  "Hindi": "hin",
  "Bengali": "ben",
  "Polish": "pol",
  "Turkish": "tur",
  "Vietnamese": "vie",
  "Thai": "tha",
  "Czech": "cze",
  "Dutch": "dut",
  "Greek": "gre",
  "Hebrew": "heb",
  "Hungarian": "hun",
  "Indonesian": "ind",
  "Malay": "may",
  "Romanian": "rum",
  "Slovak": "slo",
  "Swedish": "swe",
  "Tamil": "tam",
  "Telugu": "tel",
  "Ukrainian": "ukr",
  "Urdu": "urd",
  "Unknown": "und", // fallback
};

String completeSubtitleLanguageName(String code) {
  code = code.toLowerCase();
  for (var entry in subtitleLangMap.entries) {
    if (entry.value.toLowerCase() == code) {
      return entry.key;
    }
  }
  return code.toUpperCase(); // fallback
}
