import 'package:flutter/material.dart';
import 'package:hugeicons/hugeicons.dart';
import 'package:iconly/iconly.dart';
import 'package:iconsax/iconsax.dart';

class SettingsSearchMetadataItem {
  final String title;
  final String category;
  final String? section;
  final String? highlightTitle;
  final String? stableKey;
  final IconData? icon;
  final String? assetIcon;

  const SettingsSearchMetadataItem({
    required this.title,
    required this.category,
    this.section,
    this.highlightTitle,
    this.stableKey,
    this.icon,
    this.assetIcon,
  });
}

const settingsSearchCategoryIcons = <String, IconData>{
  'Accounts': IconlyLight.profile,
  'Common': HugeIcons.strokeRoundedBulb,
  'Backup & Restore': HugeIcons.strokeRoundedLibraries,
  'Storage Manager': Icons.storage_rounded,
  'UI': HugeIcons.strokeRoundedPaintBoard,
  'Player': HugeIcons.strokeRoundedPlay,
  'Reader': Icons.menu_book_rounded,
  'Theme': HugeIcons.strokeRoundedPaintBrush01,
  'Extensions': Icons.extension_rounded,
  'Experimental': HugeIcons.strokeRoundedInformationCircle,
  'Logs': HugeIcons.strokeRoundedFile01,
  'About': HugeIcons.strokeRoundedInformationCircle,
  'Comment System': Icons.chat_bubble_outline_rounded,
};

const settingsSearchIndex = <String, Map<String?, List<String>>>{
  'Accounts': {
    null: ['Anilist', 'MyAnimeList', 'Simkl'],
  },
  'Common': {
    null: [
      'Hide Adult Content',
      'Ask for tracking permission',
      'Show Continue Watching Card',
      'Manage Anilist Lists',
      'Manage MyAnimeList Lists',
    ],
  },
  'Backup & Restore': {
    null: ['Create Backup', 'Restore Data'],
  },
  'Storage Manager': {
    null: ['Auto-clear threshold', 'Clear image cache now', 'Factory reset'],
  },
  'UI': {
    'Common': [
      'Enable Animation',
      'Enable Ken Burns',
      'Translucent Nav',
      'Card Style',
      'History Card Style',
      'Carousel Style',
    ],
    'Extras': [
      'Glow Multiplier',
      'Radius Multiplier',
      'Blur Multiplier',
      'Card Roundness',
      'Card Animation Duration',
    ],
  },
  'Player': {
    'Common': [
      'Use LibMpv for Playback',
      'Use Libass for Subtitles',
      'Player Theme',
      'JSON Theme Manager',
      'Swipe Indicator Theme',
      'Default Portrait',
      'Playback Speed',
      'Resize Mode',
      'Auto Skip OP',
      'Auto Skip ED',
      'Auto Skip Recap',
      'Auto Skip Once Only',
      'Auto Skip Filler',
      'Enable Swipe Controls',
      'Save Last Frame',
      'Animate Control Overlay',
      'DoubleTap to Seek',
      'MegaSkip Duration',
      'Mark As Watched',
    ],
    'Subtitles': [
      'Transition Subtitle',
      'Auto Translate Subtitles',
      'Translate To',
      'Subtitle Font',
      'Outline Type',
      'Subtitle Size',
      'Subtitle Color',
      'Subtitle Transparency',
      'Subtitle Background Color',
      'Subtitle Outline Color',
      'Subtitle Outline Width',
      'Bottom Margin',
    ],
    'Experimental': [
      'Enable Experimental Settings',
      'Decoder (HWDec)',
      'Video Sync',
      'Frame Interpolation',
      'Audio Pitch Correction',
      'Cache Minutes',
      'Demuxer Readahead',
      'Demuxer Max Buffer',
      'Decoder Threads',
      'Buffer Size',
      'Auto Play',
      'Use Buffering',
    ],
  },
  'Reader': {
    'Manga': [
      'Control Theme',
      'Layout',
      'Direction',
      'Dual Page Mode',
      'Spaced Pages',
      'Overscroll',
      'Persistent Page Indicator',
      'Crop Borders',
      'Auto Scroll',
      'Auto Scroll Speed',
      'Volume Keys Navigation',
      'Invert Volume Keys',
      'Keep Screen On',
      'Auto Webtoon Mode',
      'Always Show Chapter Transition',
      'Long Press Page Actions',
    ],
    'Novel': [
      'Theme',
      'Font Family',
      'Font Size',
      'Line Height',
      'Background Opacity',
      'Letter Spacing',
      'Word Spacing',
      'Paragraph Spacing',
      'Page Reader Mode',
      'Auto Scroll',
      'Auto Scroll Speed',
      'Volume Button Scrolling',
      'Tap to Scroll',
      'Swipe Between Chapters',
      'Keep Screen On',
      'Show Reading Progress',
      'Show Battery & Time',
      'Enable TTS',
      'TTS Speed',
      'TTS Pitch',
      'TTS Auto Advance',
      'Reset Novel Reader Settings',
    ],
  },
  'Theme': {
    'Appearance': [
      'Default Theme',
      'Material You',
      'Liquid Mode',
      'Liquid Background',
      'Retain Original Color',
      'Use Poster Color',
    ],
    'Extras': [
      'Bloom',
      'Palette',
      'Oled Mode',
      'Custom Theme',
      'Logo Animation',
      'Reset to Default Picture',
    ],
  },
  'Extensions': {
    null: ['Anime', 'Manga', 'Novel'],
  },
  'Experimental': {
    'Reader': ['Cache Duration'],
  },
  'Logs': {
    null: ['Write log to a file', 'Share logs', 'Log directory'],
  },
  'About': {
    null: [
      'Telegram',
      'Discord',
      'Reddit',
      'GitHub',
      'Ko-fi',
      'Features/Issues',
      'Forks',
      'Check for Updates',
      'Enable Beta Updates',
      'Contributors',
      'Terms of Service/Privacy Policy',
      'Comment Policy',
    ],
  },
  'Comment System': {
    null: [
      'About Commentum v2',
      'User Role',
      'Moderation Panel',
      'Reported Comments',
      'Comment Preferences',
      'Notification Settings',
      'Help & Support',
      'Privacy & Safety',
    ],
  },
};

const settingsSearchTitleIcons = <String, IconData>{
  'Ask for tracking permission': Icons.touch_app_rounded,
  'Hide Adult Content': Icons.play_disabled_rounded,
  'Show Continue Watching Card': Icons.play_circle_fill_rounded,
  'Manage Anilist Lists': Icons.format_list_bulleted_sharp,
  'Manage MyAnimeList Lists': Icons.format_list_bulleted_sharp,
  'Create Backup': Icons.backup_rounded,
  'Restore Data': Icons.settings_backup_restore_rounded,
  'Auto-clear threshold': Icons.storage_rounded,
  'Clear image cache now': Icons.delete_sweep_rounded,
  'Factory reset': Icons.warning_rounded,
  'Enable Animation': HugeIcons.strokeRoundedBounceRight,
  'Enable Ken Burns': Iconsax.image,
  'Translucent Nav': Icons.colorize,
  'Card Style': Iconsax.card5,
  'History Card Style': Iconsax.card5,
  'Carousel Style': Icons.view_carousel_rounded,
  'Glow Multiplier': HugeIcons.strokeRoundedLighthouse,
  'Radius Multiplier': HugeIcons.strokeRoundedRadius,
  'Blur Multiplier': HugeIcons.strokeRoundedRadius,
  'Card Roundness': HugeIcons.strokeRoundedRadius,
  'Card Animation Duration': HugeIcons.strokeRoundedRadius,
  'Use LibMpv for Playback': Icons.subtitles,
  'Use Libass for Subtitles': Icons.subtitles,
  'Default Theme': HugeIcons.strokeRoundedPaintBrush01,
  'Custom Theme': HugeIcons.strokeRoundedColors,
  'Material You': HugeIcons.strokeRoundedImage01,
  'Liquid Mode': HugeIcons.strokeRoundedBlur,
  'Liquid Background': HugeIcons.strokeRoundedImageAdd01,
  'Retain Original Color': HugeIcons.strokeRoundedImageComposition,
  'Use Poster Color': HugeIcons.strokeRoundedImageDownload,
  'Bloom': HugeIcons.strokeRoundedFlower,
  'Palette': HugeIcons.strokeRoundedPaintBoard,
  'Oled Mode': HugeIcons.strokeRoundedMoon,
  'Logo Animation': HugeIcons.strokeRoundedPlayCircle,
  'Reset to Default Picture': HugeIcons.strokeRoundedRefresh,
  'Player Theme': HugeIcons.strokeRoundedPlaySquare,
  'Control Theme': Icons.style_rounded,
  'Reader Control Theme': Icons.style_rounded,
  'JSON Theme Manager': Icons.data_object_rounded,
  'Swipe Indicator Theme': Icons.tune_rounded,
  'Default Portrait': Icons.stay_current_portrait,
  'Playback Speed': Icons.speed,
  'Resize Mode': Icons.aspect_ratio,
  'Auto Skip OP': Icons.fast_forward,
  'Auto Skip ED': Icons.fast_forward_outlined,
  'Auto Skip Recap': Icons.fast_forward_outlined,
  'Auto Skip Once Only': Icons.all_inclusive,
  'Auto Skip Filler': Icons.skip_next_rounded,
  'Enable Swipe Controls': Icons.play_disabled_rounded,
  'Save Last Frame': Icons.screenshot_rounded,
  'Animate Control Overlay': Icons.animation_rounded,
  'DoubleTap to Seek': Iconsax.forward5,
  'MegaSkip Duration': Iconsax.forward5,
  'Mark As Watched': Iconsax.tick_circle,
  'Transition Subtitle': Icons.lightbulb,
  'Auto Translate Subtitles': HugeIcons.strokeRoundedTranslate,
  'Translate To': Icons.language,
  'Subtitle Font': Icons.font_download_rounded,
  'Outline Type': Icons.format_paint_rounded,
  'Subtitle Color': Icons.palette,
  'Subtitle Transparency': Icons.opacity,
  'Subtitle Background Color': Icons.palette,
  'Subtitle Outline Color': Icons.palette,
  'Subtitle Size': Iconsax.subtitle5,
  'Subtitle Outline Width': Iconsax.subtitle5,
  'Bottom Margin': Icons.vertical_align_bottom,
  'Enable Experimental Settings': Icons.science_outlined,
  'Decoder (HWDec)': Icons.memory_rounded,
  'Mpv Decoder (HWDec)': Icons.memory_rounded,
  'Video Sync': Icons.sync_rounded,
  'Frame Interpolation': Icons.movie_filter_rounded,
  'Audio Pitch Correction': Icons.graphic_eq_rounded,
  'Cache Minutes': Icons.timer_outlined,
  'Demuxer Readahead': Icons.downloading_rounded,
  'Demuxer Max Buffer': Icons.storage_rounded,
  'Decoder Threads': Icons.developer_board_rounded,
  'Buffer Size': Icons.storage_rounded,
  'Auto Play': Icons.play_arrow_rounded,
  'Use Buffering': Icons.network_check_rounded,
  'Layout': Iconsax.card,
  'Direction': Iconsax.direct_right,
  'Dual Page Mode': Iconsax.book_1,
  'Spaced Pages': Iconsax.pharagraphspacing,
  'Overscroll': Iconsax.arrow,
  'Persistent Page Indicator': Iconsax.eye,
  'Crop Borders': Icons.crop_rounded,
  'Auto Scroll': Icons.play_arrow_rounded,
  'Auto Scroll Speed': Icons.speed_rounded,
  'Volume Keys Navigation': Iconsax.volume_high,
  'Invert Volume Keys': Iconsax.arrow_swap_horizontal,
  'Keep Screen On': Icons.lock_clock_rounded,
  'Auto Webtoon Mode': Icons.swap_vert_rounded,
  'Always Show Chapter Transition': Icons.swap_horiz_rounded,
  'Long Press Page Actions': Icons.touch_app_rounded,
  'Novel Theme': Icons.palette_rounded,
  'Theme': Icons.palette_rounded,
  'Font Family': HugeIcons.strokeRoundedTextFont,
  'Font Size': Icons.format_size_rounded,
  'Line Height': Icons.height_rounded,
  'Background Opacity': Icons.opacity_rounded,
  'Letter Spacing': Icons.text_fields_rounded,
  'Word Spacing': Icons.text_rotation_none_rounded,
  'Paragraph Spacing': Icons.format_line_spacing_rounded,
  'Page Reader Mode': Icons.chrome_reader_mode_rounded,
  'Volume Button Scrolling': Iconsax.volume_high,
  'Tap to Scroll': Icons.touch_app_rounded,
  'Swipe Between Chapters': Icons.swipe_rounded,
  'Show Reading Progress': Icons.pie_chart_rounded,
  'Show Battery & Time': Icons.schedule_rounded,
  'Enable TTS': Icons.record_voice_over_rounded,
  'TTS Speed': Icons.slow_motion_video_rounded,
  'TTS Pitch': Icons.graphic_eq_rounded,
  'TTS Auto Advance': Icons.skip_next_rounded,
  'Reset Novel Reader Settings': Icons.restart_alt_rounded,
  'Cache Duration': Icons.extension,
  'Write log to a file': HugeIcons.strokeRoundedFile02,
  'Share logs': HugeIcons.strokeRoundedShare08,
  'Log directory': HugeIcons.strokeRoundedFolder01,
  'Anime': Icons.movie_creation_outlined,
  'Manga': Icons.menu_book_outlined,
  'Novel': Icons.auto_stories_outlined,
  'Check for Updates': Icons.system_update,
  'Enable Beta Updates': Iconsax.toggle_on,
  'Contributors': Icons.group_rounded,
  'Terms of Service/Privacy Policy': HugeIcons.strokeRoundedPolicy,
  'Comment Policy': HugeIcons.strokeRoundedAlertSquare,
  'Telegram': HugeIcons.strokeRoundedTelegram,
  'Discord': HugeIcons.strokeRoundedDiscord,
  'Reddit': HugeIcons.strokeRoundedReddit,
  'GitHub': HugeIcons.strokeRoundedGithub,
  'Ko-fi': HugeIcons.strokeRoundedCoffee01,
  'Features/Issues': Icons.bug_report,
  'Forks': Icons.call_split_rounded,
  'About Commentum v2': Icons.info_outline,
  'User Role': Icons.person_outline,
  'Moderation Panel': Icons.admin_panel_settings_outlined,
  'Reported Comments': Icons.report_outlined,
  'Comment Preferences': Icons.settings_outlined,
  'Notification Settings': Icons.notifications_outlined,
  'Help & Support': Icons.help_outline,
  'Privacy & Safety': Icons.privacy_tip_outlined,
};

const settingsSearchTitleAssetIcons = <String, String>{
  'Anilist': 'assets/images/anilist-icon.png',
  'MyAnimeList': 'assets/images/mal-icon.png',
  'Simkl': 'assets/images/simkl-icon.png',
};

final settingsSearchMetadata = <SettingsSearchMetadataItem>[
  for (final categoryEntry in settingsSearchIndex.entries)
    for (final sectionEntry in categoryEntry.value.entries)
      for (final title in sectionEntry.value)
        SettingsSearchMetadataItem(
          title: title,
          category: categoryEntry.key,
          section: sectionEntry.key,
          icon: settingsSearchTitleIcons[title],
          assetIcon: settingsSearchTitleAssetIcons[title],
        ),
  const SettingsSearchMetadataItem(
    title: 'Reader Control Theme',
    category: 'Reader',
    section: 'Manga',
    highlightTitle: 'Control Theme',
    stableKey: 'Control Theme',
    icon: Icons.style_rounded,
  ),
  const SettingsSearchMetadataItem(
    title: 'Novel Theme',
    category: 'Reader',
    section: 'Novel',
    highlightTitle: 'Theme',
    stableKey: 'Theme',
    icon: Icons.palette_rounded,
  ),
];
