name: Release choco

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-chocolatey:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Get Latest Release Info
        id: get_release
        run: |
          $release = (Invoke-RestMethod -Uri "https://api.github.com/repos/RyanYuuki/AnymeX/releases/latest")
          $exe_asset = $release.assets | Where-Object { $_.name -match 'AnymeX-x86_64-([\d.]+)-Installer\.exe' }
          $version = $matches[1]
          $exe_url = $exe_asset.browser_download_url
          $exe_content = Invoke-WebRequest -Uri $exe_url -Method Head
          $exe_hash = (Get-FileHash -InputStream $exe_content.RawContentStream -Algorithm SHA256).Hash
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "EXE_URL=$exe_url" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "EXE_HASH=$exe_hash" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Update Chocolatey Package Files
        run: |
          $version = $env:VERSION
          $exe_url = $env:EXE_URL
          $exe_hash = $env:EXE_HASH
          (Get-Content chocolatey/anymex.nuspec) -replace '<version>.*</version>', "<version>$version</version>" | Set-Content chocolatey/anymex.nuspec
          (Get-Content chocolatey/tools/chocolateyInstall.ps1) -replace '\$url = .*$', "\$url = '$exe_url'" -replace '\$checksum = .*$', "\$checksum = '$exe_hash'" | Set-Content chocolatey/tools/chocolateyInstall.ps1

      - name: Build Chocolatey Package
        run: |
          choco pack chocolatey/anymex.nuspec --outputdirectory chocolatey

      - name: Push Chocolatey Package
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
          choco push chocolatey/anymex.$env:VERSION.nupkg --source https://push.chocolatey.org/

      - name: Release Chocolatey Package
        uses: ncipollo/release-action@v1
        with:
          artifacts: "chocolatey/anymex.*.nupkg"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: ${{ github.ref_name }}
