name: Update Sideloading Source

on:
  workflow_call:
  workflow_dispatch: # Allow manual triggering of this workflow

jobs:
  update-source:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run source updater
        run: python repo/update_source.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "updated source to: $release_tag"
            git push
          fi
